# Generated by Django 5.0.6 on 2024-07-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='photoFileName',
        ),
    ]
